### ISSUE TITLE
Display GitLab ThumbsUp

### ISSUE THREAD

**Issue by agonsorcik** [nirzari/review-rot#32]
It would be great it you could display GitLab's ThumbsUp.

**Comment by nirzari** [comment]
@agonsorcik,

There is no universal standard used by people to show their approval for Gitlab. Some people tend to use '+1s' at the end of discussions, others prefer using thumbs up and many of them likes writing 'LGTM' on them, likewise for github and pagure.

Moreover, some project might just have one reviewer and some might have more than one. Hence, I am seeing no significant advantage in implementing 'no. of approvals'. (Currently, we are displaying number of comments in output string - which is sort of helpful) Also, due to different things users prefer, this feature won't be consistent. Please let me know your views.

**Comment by ralphbean** [comment]
Yeah - I think I agree with @nirzari here.

Technically we *could* try to capture all the different kinds of thumbs-ups that different systems could
encode, but that would be a losing battle.  We'd never catch every case.  The code would turn to spaghetti, fast.  :)

**Comment by nirzari** [comment]
Thanks @agonsorcik @ralphbean for your thoughts. At this point, it doesn't feel like we are benefiting from addressing this issue. Hence, I am closing it. Please feel free to raise any other issues for future enhancements. Thanks.
