### ISSUE TITLE
Get this working with that "other" gitlab instance.

### ISSUE THREAD

**Issue by ralphbean** [nirzari/review-rot#54]
This works with gitlab.cee but it doesn't work with gitlab.infra.  ;)

Anyone know why?

**Comment by nirzari** [comment]
AFAIK, the gitlab version for gitlab.infra (6.9.2) is lower than the gitlab.cee (8.14.4). Gitlab API being used here (V4) doesn't support the lower version and hence It doesn't work with gitlab.infra.

**Comment by ddelabru** [comment]
Working on this, I've run into something weird in the behavior of gitlab.infra: it responds with HTML 404 errors to API calls that contain an escaped forward slash (%2F). This is similar to a GitLab issue reported here, which was resolved by adjusting the GitLab instance configuration: https://gitlab.com/gitlab-org/gitlab-ce/issues/35079#note_76374269

I'm now attempting to communicate with the folks who run gitlab.infra to see if we can do something similar with that instance

**Comment by ddelabru** [comment]
After communication with the folks from gitlab.infra, it now serves JSON 404 responses to API get-project calls following the API v3 form documented on gitlab.infra itself. API calls to gitlab.cee formed in exactly the same way produce a JSON object containing all pertinent project metadata, as do API calls to gitlab.infra that use a numerical project ID instead of the "group-name%2Fproject" format.

The folks responsible for gitlab.infra inform me that the version of GitLab it's running has fallen far out of compatibility with python-gitlab, and also does not support a number of documented API v3 features. Attempting to a list of available projects via API v2 produced an HTML 404 error, which suggests to me that it does not have an older API version available. (Research indicates that at the time API v2 was available, the API version was identical to the GitLab major version. This has not been the case for some time.)

The JSON list of user-accessible projects I get via API v3 calls using my token for both gitlab.cee and gitlab.infra is empty, so looking using group/project name to lookup the associated numerical project ID from this list does not seem to be a viable option. Nor does finding a public project's numerical ID via the gitlab.infra web UI seem to be easy/documented.

I suspect that it will be challenging to determine whether the API provided by the particular GitLab version and configuration running on gitlab.infra can provide the functionality required by review-rot

**Comment by ddelabru** [comment]
The gitlab.infra maintainers pointed me to the API documentation hosted there, which is what I've been using. The documented API call to retrieve information on a group by name is not working for me when tested through urllib3 (404 errors again), whereas it works just fine on gitlab.cee.

The closest thing I have to a workaround is that gitlab.infra _does_ respond appropriately to the API call to get a list of user-accessible projects. However, this does not include the public projects on the GitLab server, so I don't think this makes sense for the range of review-rot use cases

**Comment by nirzari** [comment]
@ralphbean Could you please review the reasoning provided here and let us know your thoughts? Thanks

**Comment by ralphbean** [comment]
Ack - agreed with @ddelabru.  We need to upgrade gitlab.infra.  Thanks both!
